config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  # resources :descriptions
  # resources :redescriptions
  resources :projects

#  get 'recompanies', to: 'recompanies#index'
#  get 'companies', to: 'companies#index'
#  get 'companies/architects', to: 'companies#index'

  devise_for :recompanies, path: 'recompanies', controllers: {
    sessions: "recompanies/sessions",
    registrations: 'recompanies/registrations'
  }

  devise_for :companies, path: 'companies', controllers: {
    sessions: "companies/sessions",
    registrations: 'companies/registrations'
  }

  resources :recompanies, only: [:index, :show] do
    resource :redescriptions
    member do
      get 'contact'
    end
  end

  resources :companies, only: [:index, :show] do
    resource :description
    member do
      get 'contact'
    end
  end

  resources :categories
  root to: 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/redescription.rb
class Redescription < ApplicationRecord
  belongs_to :recompany
end

app/controllers/redescriptions_controller.rb
class RedescriptionsController < ApplicationController
  before_action :set_redescription, only: [:show, :edit, :update, :destroy]

  # GET /redescriptions
  # GET /redescriptions.json
  def index
    @redescriptions = Redescription.all
  end

  # GET /redescriptions/1
  # GET /redescriptions/1.json
  def show
  end

  # GET /redescriptions/new
  def new
    # @recompany = Recompany.find(params[:recompany_id])
    @redescription = Redescription.new
  end

  # GET /redescriptions/1/edit
  def edit
  end

  # POST /redescriptions
  # POST /redescriptions.json
  def create
    @redescription = Redescription.new(redescription_params2)
    @redescription.recompany_id = redescription_params[:recompany_id]

    if Recompany.find(params[:recompany_id]).redescription != nil
      respond_to do |format|
        format.html { redirect_to recompany_path(@redescription.recompany_id), notice: 'No se puede guardar, ya existe una descripción' }
      end
    else
      respond_to do |format|
        if @redescription.save
          format.html { redirect_to recompany_path(@redescription.recompany_id), notice: 'Redescription was successfully created.' }
          format.json { render :show, status: :created, location: @redescription }
        else
          format.html { render :new }
          format.json { render json: @redescription.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /redescriptions/1
  # PATCH/PUT /redescriptions/1.json
  def update
    respond_to do |format|
      if @redescription.update(redescription_params)
        format.html { redirect_to @redescription, notice: 'Redescription was successfully updated.' }
        format.json { render :show, status: :ok, location: @redescription }
      else
        format.html { render :edit }
        format.json { render json: @redescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /redescriptions/1
  # DELETE /redescriptions/1.json
  def destroy
    @redescription.destroy
    respond_to do |format|
      format.html { redirect_to redescriptions_url, notice: 'Redescription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_redescription
      @recompany = Recompany.find(params[:recompany_id])
      @redescription = @recompany.redescription
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def redescription_params
      # params.require(:redescription).permit(:image, :ppal_title, :ppal_content, :second_title, :second_content, :terc_title, :terc_content, :redescription => [:image, :ppal_title, :ppal_content, :second_title, :second_content, :terc_title, :terc_content])
      params.permit(:recompany_id)
    end

    def redescription_params2
      params.require(:redescription).permit(:image, :ppal_title, :ppal_content, :second_title, :second_content, :terc_title, :terc_content)
    end


end

app/helpers/redescriptions_helper.rb
module RedescriptionsHelper
end

app/views/redescriptions/_form.html.erb
<%= form_with(model: redescription, local: true) do |form| %>
  <% if redescription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(redescription.errors.count, "error") %> prohibited this redescription from being saved:</h2>

      <ul>
      <% redescription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :ppal_title %>
    <%= form.text_field :ppal_title %>
  </div>

  <div class="field">
    <%= form.label :ppal_content %>
    <%= form.text_area :ppal_content %>
  </div>

  <div class="field">
    <%= form.label :second_title %>
    <%= form.text_field :second_title %>
  </div>

  <div class="field">
    <%= form.label :second_content %>
    <%= form.text_area :second_content %>
  </div>

  <div class="field">
    <%= form.label :terc_title %>
    <%= form.text_field :terc_title %>
  </div>

  <div class="field">
    <%= form.label :terc_content %>
    <%= form.text_area :terc_content %>
  </div>

  <div class="field">
    <%= form.label :recompany_id %>
    <%= form.text_field :recompany_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/redescriptions/edit.html.erb
<h1>Editing Redescription</h1>

<%= render 'form', redescription: @redescription %>

<%= link_to 'Show', @redescription %> |
<%= link_to 'Back', redescriptions_path %>

app/views/redescriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Redescriptions</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Ppal title</th>
      <th>Ppal content</th>
      <th>Second title</th>
      <th>Second content</th>
      <th>Terc title</th>
      <th>Terc content</th>
      <th>Recompany</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @redescriptions.each do |redescription| %>
      <tr>
        <td><%= redescription.image %></td>
        <td><%= redescription.ppal_title %></td>
        <td><%= redescription.ppal_content %></td>
        <td><%= redescription.second_title %></td>
        <td><%= redescription.second_content %></td>
        <td><%= redescription.terc_title %></td>
        <td><%= redescription.terc_content %></td>
        <td><%= redescription.recompany %></td>
        <td><%= link_to 'Show', redescription %></td>
        <td><%= link_to 'Edit', edit_redescription_path(redescription) %></td>
        <td><%= link_to 'Destroy', redescription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Redescription', new_redescription_path %>

app/views/redescriptions/new.html.erb
<h1>New Redescription</h1>

<%= form_with(url: recompany_redescriptions_path, scope: :redescription, model: [@recompany, @redescription], local: true) do |form| %>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :ppal_title %>
    <%= form.text_field :ppal_title %>
  </div>

  <div class="field">
    <%= form.label :ppal_content %>
    <%= form.text_area :ppal_content %>
  </div>

  <div class="field">
    <%= form.label :second_title %>
    <%= form.text_field :second_title %>
  </div>

  <div class="field">
    <%= form.label :second_content %>
    <%= form.text_area :second_content %>
  </div>

  <div class="field">
    <%= form.label :terc_title %>
    <%= form.text_field :terc_title %>
  </div>

  <div class="field">
    <%= form.label :terc_content %>
    <%= form.text_area :terc_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', recompany_path(id: params[:recompany_id]) %>

app/views/redescriptions/show.html.erb
<p id="notice"><%= notice %></p>

<% if @recompany.logo.url.present? %>
<%=link_to( image_tag(@recompany.logo.url, size:"240x240", class:"img-fluid d-block"), @recompany) %>
<% else %>
<%= image_tag "http://placehold.it/640x480", class:"img-fluid d-block" %>
<% end %>

<br>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="<%= recompany_path(id: params[:recompany_id]) %>">Nuestros Proyectos</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Empresa</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= contact_recompany_path(@recompany) %>">Contacto</a>
  </li>
</ul>

<br>


<div class=""><%= image_tag "construction-team", class:"img-fluid d-block" %>

</div>

<div class="py-5" >
  <div class="container">
    <div class="row">
      <div class="col-md-10">
        <h1 class="mb-3"><%= @redescription.ppal_title %></h1>
        <p><%= @redescription.ppal_content %></p>
        <br>
        <h1 class="mb-3"><%= @redescription.second_title %></h1>
        <p><%= @redescription.second_content %></p>
        <br>
        <h1 class="mb-3"><%= @redescription.terc_title %></h1>
        <p><%= @redescription.terc_content %></p>




      </div>
    </div>
  </div>
</div>


<p>
  <strong>Image:</strong>
  <%= @redescription.image %>
</p>




<%= link_to 'Edit', "" %> |
<%= link_to 'Back', recompany_path(id: params[:recompany_id]) %>