config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  # resources :descriptions
  # resources :redescriptions
  resources :projects

#  get 'recompanies', to: 'recompanies#index'
#  get 'companies', to: 'companies#index'
#  get 'companies/architects', to: 'companies#index'

  devise_for :recompanies, path: 'recompanies', controllers: {
    sessions: "recompanies/sessions",
    registrations: 'recompanies/registrations'
  }

  devise_for :companies, path: 'companies', controllers: {
    sessions: "companies/sessions",
    registrations: 'companies/registrations'
  }

  resources :recompanies, only: [:index, :show] do
    resource :redescriptions
    member do
      get 'contact'
    end
  end

  resources :companies, only: [:index, :show] do
    resource :description
    member do
      get 'contact'
    end
  end

  resources :categories
  root to: 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to :category
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :project_companies
  has_many :projects, through: :project_companies
  has_one :description
  mount_uploader :logo, CompaniesLogoUploader
end

app/controllers/companies/confirmations_controller.rb
# frozen_string_literal: true

class Companies::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/companies/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Companies::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/companies/passwords_controller.rb
# frozen_string_literal: true

class Companies::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/companies/registrations_controller.rb
# frozen_string_literal: true

class Companies::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up,
      keys: [:name, :logo, :address, :telephone, :rut,
      :legal_name, :line_of_bussiness, :admin_name,
      :admin_email, :admin_telephone, :category_id])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies/sessions_controller.rb
# frozen_string_literal: true

class Companies::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/companies/unlocks_controller.rb
# frozen_string_literal: true

class Companies::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    if params[:category].blank?
      @companies = Company.all.order("created_at ASC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @companies = Company.where(category_id: @category_id).order("created_at ASC")
    end
  end

  def show
    @company = Company.find(params[:id])
  	# @projects = Project.where(recompany_id: params[:id]).order("created_at ASC")
  end

  def contact
    @company = Company.find(params[:id])
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/contact.html.erb
<p id="notice"><%= notice %></p>

<% if @company.logo.url.present? %>
<%=link_to( image_tag(@company.logo.url, size:"240x240", class:"img-fluid d-block"), @company) %>
<% else %>
<%= image_tag "http://placehold.it/640x480", class:"img-fluid d-block" %>
<% end %>

<br>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="<%= company_path(id: params[:id]) %>">Nuestros Proyectos</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= company_description_path(@company) %>">Empresa</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="">Contacto</a>
  </li>
</ul>

<br>


<div class="pb-5" >
  <div class="container-fluid p-0"> <%= image_tag 'foto-planos3', style: 'max-height:30%;width:100%;' %> </div>

  <div class="container">
    <div class="row">
      <div class="mx-auto p-4 col-md-6 margint5b10">
        <h2 class="mb-4">Es bueno comunicarnos</h2>
        <p>Porque nos interesa e importa tu opinión, ponemos a tu disposición este espacio para que puedas expresar tus comentarios, reclamos, felicitaciones e inquietudes; estos nos permitirán seguir mejorando nuestro servicio. <br> <br>Queremos resolver todas tus inquietudes, por eso recibiremos tu mensaje y te ayudaremos lo antes posible</p>

      </div>
      <div class="mx-auto p-4 col-md-6 margint5b10">
        <h2 class="mb-4">Envíanos un mensaje:</h2>
        <form>
          <div class="form-group"> <input type="email" class="form-control" id="form31" placeholder="Email"> </div>
          <div class="form-group"> <textarea class="form-control" id="form32" rows="3" placeholder="Ingresa tu mensaje"></textarea> </div> <button type="submit" class="btn btn-primary">Send</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>
<br>

<% @companies.each do |company| %>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6">

          <% if company.logo.url.present? %>
          <%=link_to( image_tag(company.logo.url, size:"240x240", class:"img-fluid d-block"), company) %>
          <% else %>
          <%= image_tag "http://placehold.it/640x480", class:"img-fluid d-block" %>
          <% end %>

        </div>
        <div class="px-md-5 p-3 col-md-6 d-flex flex-column justify-content-center">
          <h1><%= company.name %></h1>
          <p class="mb-3 lead"><i class="fas text-primary mr-2 fa-globe-americas"></i><%= company.address %><br></p>
          <p class="mb-2"><i class="fas text-primary mr-2 fa-phone"></i><%= company.telephone %><br></p>
          <div class="row">
            <div class="col-md-12"> <a href="#">
                <i class="fa fa-stop-circle fa-3x mr-3 text-muted d-inline"></i>
              </a> <a href="#">
                <i class="fa fa-circle-o fa-3x mx-3 text-muted d-inline"></i>
              </a> <a href="#">
                <i class="fa fa-stop-circle-o fa-3x mx-3 text-muted d-inline"></i>
              </a> <a href="#">
                <i class="fa fa-circle fa-3x ml-3 text-muted d-inline"></i>
              </a> </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<% if @company.logo.url.present? %>
<%= image_tag(@company.logo.url, size:"240x240", class:"img-fluid d-block") %>
<% else %>
<%= image_tag "http://placehold.it/640x480", class:"img-fluid d-block" %>
<% end %>

<br>

<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" href="#">Nuestros Proyectos</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= company_description_path(@company) %>">Empresa</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="<%= contact_company_path(@company) %>">Contacto</a>
  </li>
</ul>

<br>
<br>
<div class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <div class="text-center mx-auto col-lg-12 col-10">
          <div id="carousel1" class="carousel slide carousel-fade" data-ride="carousel" data-interval="5000">
            <div class="carousel-inner">
              <div class="carousel-item active"> <%= image_tag "portfolio-1", class:"d-block w-100" %> </div>
              <div class="carousel-item"> <%= image_tag "portfolio-2", class:"d-block w-100" %> </div>
              <div class="carousel-item"> <%= image_tag "portfolio-3", class:"d-block w-100" %> </div>
              <div class="carousel-item"> <%= image_tag "portfolio-4", class:"d-block w-100" %> </div>
            </div>
            <ol class="carousel-indicators">
              <li data-target="#carousel1" data-slide-to="0" class="active"> </li>
              <li data-target="#carousel1" data-slide-to="1"> </li>
              <li data-target="#carousel1" data-slide-to="2"> </li>
              <li data-target="#carousel1" data-slide-to="3"> </li>
            </ol>
          </div>
        </div>
      </div>
      <div class="col-md-1">

      </div>
      <div class="col-md-4">
        <h2 class="mb-4">Nuestra Experiencia</h2>
        <p>En este espacio puedes ver una muestra de nuestra vasta experiencia en construcción. <br> <br>Estamos abiertos a nuevos desafíos, contáctanos y haznos partícipes de tus proyectos.</p>

      </div>
    </div>
  </div>
</div>


<%= link_to 'New Project', new_project_path %>