config/routes.rb
Rails.application.routes.draw do
  get 'homes/index'
  # resources :descriptions
  # resources :redescriptions
  resources :projects

#  get 'recompanies', to: 'recompanies#index'
#  get 'companies', to: 'companies#index'
#  get 'companies/architects', to: 'companies#index'

  devise_for :recompanies, path: 'recompanies', controllers: {
    sessions: "recompanies/sessions",
    registrations: 'recompanies/registrations'
  }

  devise_for :companies, path: 'companies', controllers: {
    sessions: "companies/sessions",
    registrations: 'companies/registrations'
  }

  resources :recompanies, only: [:index, :show] do
    resource :redescriptions
    member do
      get 'contact'
    end
  end

  resources :companies, only: [:index, :show] do
    resource :description
    member do
      get 'contact'
    end
  end

  resources :categories
  root to: 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :companies
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to :category
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :project_companies
  has_many :projects, through: :project_companies
  has_one :description
  mount_uploader :logo, CompaniesLogoUploader
end

app/models/company_ability.rb
class CompanyAbility
  include CanCan::Ability

  def initialize(model)
    case model
    when Company
      can :read, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

  end
end

app/models/description.rb
class Description < ApplicationRecord
  belongs_to :company
end

app/models/guest_ability.rb
class GuestAbility
  include CanCan::Ability

  def initialize
    can :read, :all
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :recompany
  has_many :project_companies, inverse_of: :project, dependent: :destroy
  has_many :companies, through: :project_companies
  accepts_nested_attributes_for :project_companies,
  reject_if: lambda { |attributes| attributes['company_id'].blank? }
  mount_uploader :main_image, MainImageUploader
  enum role: {casa: 0, departamento: 1}
end

app/models/project_company.rb
class ProjectCompany < ApplicationRecord
  belongs_to :project
  belongs_to :company
end

app/models/recompany.rb
class Recompany < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects
  has_one :redescription
  mount_uploader :logo, RecompaniesLogoUploader
end

app/models/recompany_ability.rb
class RecompanyAbility
  include CanCan::Ability

	def initialize(recompany)
    can :read, Project
    can [:create, :update, :destroy], Project, recompany_id: recompany.id
	end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/redescription.rb
class Redescription < ApplicationRecord
  belongs_to :recompany
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/descriptions_helper.rb
module DescriptionsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/recompanies_helper.rb
module RecompaniesHelper
end

app/helpers/redescriptions_helper.rb
module RedescriptionsHelper
end

app/views/layouts/_footer.html.erb
<div class="container-fluid footer">
  <div class="container">


    <div class="row">
      <div class="p-4 col-md-3">
        <h2 class="mb-4">Construcción</h2>
        <p>Liderando el progreso de Chile</p>
      </div>
      <div class="p-4 col-md-3">
        <h2 class="mb-4">Mapa del sitio</h2>
        <ul class="list-unstyled"> <a href="<%= root_path %>" class="text-dark">Home</a> <br> <a href="<%= projects_path %>" class="text-dark">Proyectos</a> <br> <a href="<%= recompanies_path %>" class="text-dark">Inmobiliarias</a> <br> <a href="<%= companies_path %>" class="text-dark">Empresas</a> </ul>
      </div>
      <div class="p-4 col-md-3">
        <h2 class="mb-4">Contacto</h2>
        <p class="text-dark">
            <i class="fa d-inline mr-3 text-muted fa-phone"></i>+56-246681179 </p>
        <p class="text-dark">
            <i class="fa d-inline mr-3 text-muted fa-envelope-o"></i>info@construccion.com </p>
        <p class="text-dark">
            <i class="fa d-inline mr-3 fa-map-marker text-muted"></i>Av. Nueva Providencia 2060. R.M. </p>
      </div>
      <div class="p-4 col-md-3">
        <h2 class="mb-4">Subscríbete</h2>
        <form>
          <fieldset class="form-group"> <label for="exampleInputEmail1">Obtén nuestro newsletter</label> <input type="email" class="form-control" placeholder="email"> </fieldset> <button type="submit" class="btn btn-outline-dark">Submit</button>
        </form>
      </div>
    </div>
    <div class="row">

    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">Construcción<a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item  active">
        <a class="nav-link" href="<%= projects_path %>">Proyectos</a>
      </li>
      <li class="nav-item  active dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Empresas</a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= recompanies_path %>">Inmobiliarias</a>
          <a class="dropdown-item" href="<%= companies_path(category: 'Constructoras') %>">Constructoras</a>
          <a class="dropdown-item" href="<%= companies_path(category: 'Arquitectos') %>">Arquitectos</a>
          <a class="dropdown-item" href="<%= companies_path(category: 'Ingenieros') %>">Ingenieros</a>
        </div>
      </li>
      <li class="nav-item  active dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <% if company_signed_in? || recompany_signed_in? %>
          Cerrar Sesión
        <% else %>
          Acceso
        <% end %>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if company_signed_in? %>
            <a class="dropdown-item" href="<%= destroy_company_session_path %>" data-method="DELETE">Salir (Company)</a>
          <% elsif recompany_signed_in? %>
            <a class="dropdown-item" href="<%= destroy_recompany_session_path %>" data-method="DELETE">Salir (recompany)</a>

          <% else %>
            <a class="dropdown-item" href="<%= new_recompany_session_path %>">Ingreso Inmobiliarias</a>
            <a class="dropdown-item" href="<%= new_recompany_registration_path %>">Registro Inmobiliarias</a>
            <a class="dropdown-item" href="<%= new_company_session_path %>">Ingreso Empresas</a>
            <a class="dropdown-item" href="<%= new_company_registration_path %>">Registro Empresas</a>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Const2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script> -->
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">




    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="general">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>